### Add user account
POST http://localhost:4000/users/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkcmlhbmpvc2VmZXJyZXJAZ21haWwuY29tIiwicG9zaXRpb24iOiJhZG1pbiIsImlhdCI6MTY1NjE0NjE0NiwiZXhwIjoxNjU2MTQ2MjA2fQ.Hyi0uwbZnCr8lFux5pTofhlOo8-phQBmSq6rTZ4iF0E

{
    "email": "edrianj@gmail.com",
    "position": "admin"
}

### Create user account
POST http://localhost:4000/users/create/
Content-Type: application/json

{
    "email": "edrianjoseferrer@gmail.com",
    "name": "Edrian Ferrer",
    "password": "edrian"
}

### Update user account
POST http://localhost:4000/users/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkcmlhbmpvc2VmZXJyZXJAZ21haWwuY29tIiwicG9zaXRpb24iOiJhZG1pbiIsImlhdCI6MTY1NjE0NjE0NiwiZXhwIjoxNjU2MTQ2MjA2fQ.Hyi0uwbZnCr8lFux5pTofhlOo8-phQBmSq6rTZ4iF0E

{
    "_id": "62b6c8e2e1925abb6225a7f3",
    "name": "Edrian Jose Ferrer"
}